--- #YAML:1.0
name:                Test-ISBN
version:             2.01
abstract:            Check International Standard Book Numbers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Business::ISBN:                2.0
    Test::Builder::Tester:         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
