--- #YAML:1.0
name:                Test-ISBN
version:             1.09
abstract:            Check International Standard Book Numbers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Business::ISBN:                0
    Test::Builder::Tester:         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
